import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Toaster } from "sonner";
import { Providers } from "./providers";
import { AuthGuard } from "../components/context/authGuard";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <AuthGuard>
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </AuthGuard>
      </body>
    </html>
  );
}
