import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Navbar from "./components/navbar";
import { Toaster } from "sonner";
import { Providers } from "./providers";

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <Providers>
          {/* TODO: This should only show up on the landing page */}
          {/* <Navbar /> */}
          {children}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
